services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  backend:
    image: yotaka99/thai-dict-api:latest
    container_name: thai-swedish-dict-api
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  frontend:
    image: yotaka99/thai-dict-web:latest
    container_name: thai-swedish-dict-web
    environment:
      - NEXT_PUBLIC_API_URL=https://dictionary.yotakadev.com
      - BACKEND_URL=http://backend:10000
    restart: always
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
